### ISSUE TITLE
Переход от мотора к переключателю

### ISSUE THREAD

**Issue by lucky-strike7** [InfernaLEVP/Cyber_bug#10]
Здесь нужен переход какой-то. Предлагаю чтобы картинка уезжала наверх.

**Comment by lucky-strike7** [comment]
Блин я забыл что внизу то нет ничего. Не знаю пока что делать, пусть повисит. Ну самое простое по опасити убрать но это хз как будет смотреться.

**Comment by InfernaLEVP** [comment]
> Блин я забыл что внизу то нет ничего. Не знаю пока что делать, пусть повисит. Ну самое простое по опасити убрать но это хз как будет смотреться.

Можно попробовать отрендерить сцену перехода

**Comment by lucky-strike7** [comment]
Сейчас тут хорошо все выглядит. Плохо то что по прозрачности сцена убирается когда синий провод еще не прилетел на свое место. Предлагаю убирать по прозрачности когда все провода стоят на месте, то есть на последнем кадре.
