### ISSUE TITLE
Переворот жука после крыльев, перед прилетом ног. И поворот после ног обратно вниз

### ISSUE THREAD

**Issue by lucky-strike7** [InfernaLEVP/Cyber_bug#12]
Можно эти моменты замедлить в два раза, сейчас слишком быстро вращается, а это прикольные моменты. Для этого надо количество кадров больше делать?

**Comment by InfernaLEVP** [comment]
Увеличить плотность кадров на повороте "Брюшка", там сейчас 7 кадров до появления ног
Сделать около 20 бы

**Comment by lucky-strike7** [comment]
Ок, сделаем
