### ISSUE TITLE
Надпись со светодиодами остается на экране после второго пролистывания

### ISSUE THREAD

**Issue by strangesound** [InfernaLEVP/Cyber_bug#14]
Сначала все норм работает, а когда потаскаешь вперед/назад — остается

**Comment by lucky-strike7** [comment]
Это поправлено, можно закрывать

**Comment by strangesound** [comment]
Не,  иногда остается. 
<img width="1792" alt="Screenshot 2020-09-11 at 09 05 03" src="https://user-images.githubusercontent.com/42893513/92871826-06dba980-f40e-11ea-8b9d-313d3486c1a3.png">
