### ISSUE TITLE
Добавить ссылку сверху

### ISSUE THREAD

**Issue by lucky-strike7** [InfernaLEVP/Cyber_bug#21]
С текста в правом верхнем углу (PETROVICH BROTHERS FOR AMPERKA) сделать ссылку на наш сайт https://www.petrovichbrothers.ru

Никак изменяться и подсвечиваться дополнительно этот текст не должен

**Comment by strangesound** [comment]
Артем, нам бы поставить счетчик переходов, метрику

**Comment by InfernaLEVP** [comment]
> Артем, нам бы поставить счетчик переходов, метрику

utm-метку или там цели можно настроивать вроде в метрике
