### ISSUE TITLE
Добавить ссылку в конце

### ISSUE THREAD

**Issue by lucky-strike7** [InfernaLEVP/Cyber_bug#22]
С кнопки "заказать дизайн"  на мой вотсап:

https://api.whatsapp.com/send?phone=79151978652&text=Добрый день! Хотим сделать с вами проект.

**Comment by lucky-strike7** [comment]
Не, вот такую ссылку, поменял в ней текст сообщения:

https://api.whatsapp.com/send?phone=79151978652&text=Здравствуйте! Хотим сделать с вами проект.

**Comment by strangesound** [comment]
Полагаю текст в ссылке должен быть в кавычках

https://api.whatsapp.com/send?phone=79151978652&text="Здравствуйте! Хотим сделать с вами проект."
