### ISSUE TITLE
Задержка светодиода

### ISSUE THREAD

**Issue by lucky-strike7** [InfernaLEVP/Cyber_bug#5]
Нужно чтоб центральная часть диода с надписью про минусовой контакт при скролле задерживалась примерно как надпись "Как собрать". А то он прям сразу уезжает.

<img width="1368" alt="Screenshot 2020-09-07 at 13 43 40" src="https://user-images.githubusercontent.com/6556410/92379634-7866df80-f110-11ea-82ad-a787480eebed.png">

**Comment by InfernaLEVP** [comment]
Знак минусового контакта лучше перенести на секвенцию, задержку сделал

**Comment by lucky-strike7** [comment]
Ага, знак минусового контакта поставим на секвенцию

**Comment by lucky-strike7** [comment]
Почти так. Сейчас он увеличивается, потом на два кадра уменьшается и идет задержка. Надо переместить задержку где он максимального размера, на два кадра назад.
