### ISSUE TITLE
Поворот жука по вертикали после взрыва

### ISSUE THREAD

**Issue by lucky-strike7** [InfernaLEVP/Cyber_bug#7]
Как-то дергается сильно первый кадо поворота, это нам надо секвенцию поправить? Вот тут:

<img width="1354" alt="Screenshot 2020-09-07 at 14 08 13" src="https://user-images.githubusercontent.com/6556410/92381460-941fb500-f113-11ea-9f75-50030ade4eec.png">

**Comment by InfernaLEVP** [comment]
Да, увеличить секвенцию, там всего 6 кадров на этот поворот

**Comment by lucky-strike7** [comment]
Ок, сделаем
