### ISSUE TITLE
Сцена с мотором не правильно скейлится

### ISSUE THREAD

**Issue by lucky-strike7** [InfernaLEVP/Cyber_bug#8]
Сейчас секвенции скейлятся вместе с окном, из за этого картинка может быть непропорционально сжата. Думаю что надо приклеить секвенцию к верхнему и к нижнему краю.

**Comment by lucky-strike7** [comment]
У меня вроде работает нормально уже все?

**Comment by strangesound** [comment]
Скейлы надо везде поправить — 
Полноэкранные привязать к верху и низу, а ширину оставить свободно пропорционально изменяться

**Comment by strangesound** [comment]
<img width="1097" alt="Screenshot 2020-09-10 at 21 46 05" src="https://user-images.githubusercontent.com/42893513/92872158-63d75f80-f40e-11ea-86db-af2c4a2c2d6c.png">
<img width="1097" alt="Screenshot 2020-09-10 at 21 45 54" src="https://user-images.githubusercontent.com/42893513/92872179-689c1380-f40e-11ea-9fd6-2da952091570.png">
<img width="1568" alt="Screenshot 2020-09-10 at 21 44 59" src="https://user-images.githubusercontent.com/42893513/92872182-69cd4080-f40e-11ea-85fe-4ee032720ab8.png">
